Innovate-Future-Foundation/frontend

.github/pull_request_template.md
This PR updated PR template.
- updated PR template.
- checked inspector read.
[JIRA Ticket: IF-93](https://dext.atlassian.net/jira/software/c/projects/IF/boards/26?selectedIssue=IF-93)
=> refactor: update pr template

package-lock.json, package.json, src/components/Header/AvatarDropdownMenu.tsx, src/components/ui/dropdown-menu.tsx
This PR introduces the Avatar Dropdown Menu component.
- Avatar Dropdown Menu: Added a component for pop up a dropdown menu for editing profile and logout.
manual test: render component on browser.
Related Ticket
[JIRA Ticket: IF-109](https://dext.atlassian.net/jira/software/c/projects/IF/boards/26?selectedIssue=IF-109)
=> feat: add avator dropdown menu

src/pages/Organisation/OrganisationDetailPage.tsx
This PR ...
- Move ScrollList component to OrganisationDetailPage for better logical structure.
- Add placeholder for future Organisation Detail component
- Maintain existing ScrollList styling and functionality
- Open the Organisation Detail page in browser
- 
[JIRA Ticket: IF-128](https://dext.atlassian.net/jira/software/c/projects/IF/boards/26?selectedIssue=IF-128)
=> refactor: optimize ScrollList layout and placement

src/components/ScrollList/ScrollItem.tsx, src/pages/Dashboard/Breadcrumb.tsx, src/pages/Dashboard/DashboardContent.tsx, src/pages/Dashboard/Sidebar.tsx
This PR has Created General Breadcrumb Component for Dashboard Child Pages
Centralized Dashboard Menu Data Management: 
- Moved dashboard menu configuration to a single source of truth for easier maintenance and consistency across the application.
Dynamic Breadcrumb Component: 
- Implemented a reusable breadcrumb component that dynamically tracks the current path. 
- Supports custom menu names, including nested routes with dynamic segments.
Performed manual testing in the browser to verify:
- Breadcrumbs accurately reflect the current path.
- Dynamic segments (e.g., /dashboard/organisation/:id) are handled correctly.
- Custom menu names render as expected.
[JIRA Ticket: IF-175](https://dext.atlassian.net/jira/software/c/projects/IF/board …
=> feat 175: breadcrumb component

src/components/RemoveModal/index.tsx, src/components/ScrollList/ScrollItem.tsx
This PR ...
- implement the component of remove users
- fit it in the trash item of the invitee list
- in real pages
- 
[JIRA Ticket: IF-108](https://dext.atlassian.net/jira/software/c/projects/IF/boards/26?selectedIssue=IF-108)
=> feat: implement remove modal UI and basic interaction

package-lock.json, package.json, src/pages/Authentication/index.tsx, src/pages/Authentication/loginform.tsx, tailwind.config.js
This PR introduces animations to the Authentication Page using the tailwindcss-motion package, enhancing user experience with smoother visual effects.
- Installed the tailwindcss-motion package to enable animations.
- Applied animation effects to components on the authentication page for improved interactivity and responsiveness.
- Verified animations and component behaviors through manual testing in the browser.
[JIRA Ticket: IF-203](https://dext.atlassian.net/jira/software/c/projects/IF/boards/26?selectedIssue=IF-203)
=> feat: add animation to login page

src/pages/Authentication/index.tsx, src/pages/Dashboard/Sidebar.tsx, src/pages/Dashboard/index.tsx
This PR Fix Unique Key Issue and Header Span Visibility in Sidebar
- Resolved the unique key issue in the Sidebar component to eliminate React warnings and ensure proper rendering.
- Addressed the header span hidden issue, ensuring consistent visibility and alignment in the header.
- Verified fixes through manual testing across multiple scenarios to confirm functionality.
[JIRA Ticket: IF-220](https://dext.atlassian.net/jira/software/c/projects/IF/boards/26?selectedIssue=IF-220)
=> fix: unique key issue in sidebar; header span hidden issue; 

src/app/main.tsx
This PR configured toast in main.tsx
- add Toaster in main.tsx
- add a button to manually test.
**sample code:**
```javascript
onClick={() => {
toast({
title: "Scheduled: Catch up ",
description: "Friday, February 10, 2023 at 5:57 PM",
action: (
<ToastAction altText="Goto schedule to undo">Undo</ToastAction>
),
})
}}
```
[JIRA Ticket: IF-223](https://dext.atlassian.net/jira/software/c/projects/IF/boards/26?selectedIssue=IF-223)
=> feat: config toast

src/pages/Dashboard/Sidebar.tsx
This PR fixed arrow icon does not rotate issue.
- Resolved the issue where the arrow icon did not rotate during row collapse and expansion.
- Verified that the arrow icon rotates correctly when rows are expanded or collapsed.
[JIRA Ticket: IF-224](https://dext.atlassian.net/jira/software/c/projects/IF/boards/26?selectedIssue=IF-224)
=> fix: fix arrow does not move issue

src/components/DataTable/index.tsx, src/pages/Contacts/contactsColumns.tsx, src/pages/Contacts/index.tsx, src/pages/Dashboard/SidebarMenu.ts, src/pages/Dashboard/index.tsx, src/pages/Profile/index.tsx, src/routes/index.tsx
This PR refactored table into cards.
- make contacts table list into cards.
- manual test
[JIRA Ticket: IF-222](https://dext.atlassian.net/jira/software/c/projects/IF/boards/26?selectedIssue=IF-222)
=> feat: add contact cards

src/utils/formatters.ts
This PR revert convertToQueryParams util func
- Revert convertToQueryParams util func.
- manual test
[JIRA Ticket: IF-253](https://dext.atlassian.net/jira/software/c/projects/IF/boards/26?selectedIssue=IF-253)
=> fix: revert convertToQueryParams util func

.env.example, .gitignore, src/pages/OrgAdmin/index.tsx
This PR added env example
- added env example
- manual test
[JIRA Ticket: IF-257](https://dext.atlassian.net/jira/software/c/projects/IF/boards/26?selectedIssue=IF-257)
=> feat: add env example

src/app/index.css, src/hooks/useAuth.ts, src/pages/Authentication/LoginForm.tsx, src/pages/Authentication/index.tsx, src/pages/Dashboard/Sidebar.tsx
This PR Fixes Inconsistencies Between Mobile and Desktop States
- Add
`--sidebar-background: 217 65% 100%;
--sidebar-border: 220 13% 80%;
`
- Resolved Inconsistent State Handling → Fixed discrepancies between isMobile state and desktop behavior.
- Enhanced Sidebar Styling → Added the following CSS variables for improved theming:
- Manual Testing → Verified layout adjustments, sidebar behavior, and state transitions across mobile and desktop devices.
[JIRA Ticket: IF-263](https://dext.atlassian.net/jira/software/c/projects/IF/boards/26?selectedIssue=IF-263)
=> fix: fixed inconsist sidebar bg color issue

.github/pull_request_template.md, src/pages/Dashboard/SidebarMenu.ts, src/routes/index.tsx
This PR removed users from roleType.
[JIRA Ticket: IF-284](https://dext.atlassian.net/browse/IF-284)
=> fix: remove users from roletype

src/app/index.css, src/components/DataTable/index.tsx, src/components/Tooltip/index.tsx, src/components/ui/tooltip.tsx, src/pages/Organisation/orgColumns.tsx, src/pages/Profile/profileColumns.tsx
This PR had done some minor tweaks.
- re-aligned loader component.
- add tooltip component for table email column
[JIRA Ticket: IF-274](https://dext.atlassian.net/browse/IF-274)
=> feat: tooltip for email; re-align loader to center

src/components/Header/SignInAvatar.tsx, src/hooks/auth/useLogin.ts, src/hooks/auth/useLogout.ts, src/hooks/auth/useRegister.ts, src/hooks/useAuth.ts, src/pages/Authentication/ForgotPasswordForm.tsx, src/pages/Authentication/LoginForm.tsx, src/pages/Authentication/RegisterForm.tsx, src/store/useTourBuilderStore.ts
This PR added login and logout api.
- added login and logout api.
[JIRA Ticket: IF-311](https://dext.atlassian.net/browse/IF-311)
=> feat: add login and logout

src/app/App.test.tsx, src/components/Header/index.tsx, src/components/ProtectedRoute/ProtectedRoute.tsx, src/constants/apiConfig.ts, src/hooks/auth/useGetMe.ts, src/layouts/MainLayout/index.tsx, src/queries/auth.ts, src/routes/index.tsx, src/services/apiServices/authApis.ts
This PR added getMe api.
- added getMe api.
[JIRA Ticket: IF-338](https://dext.atlassian.net/browse/IF-338)
=> feat: add getMe api

src/pages/Authentication/RegisterForm.tsx
This PR fixed setFocus not working issue.
- add setTimeout for setFocus to wait animation done
[JIRA Ticket: IF-339](https://dext.atlassian.net/browse/IF-339)
=> fix: add settimeout for setfocus to wait animation done

src/components/Breadcurmb/index.tsx, src/components/DataTable/index.tsx, src/components/FormField/index.tsx, src/components/Header/SignInAvatar.tsx, src/components/Header/index.tsx, src/components/Pagenation/index.tsx, src/layouts/ContentLayout/index.tsx, src/layouts/MainLayout/index.tsx, src/pages/Authentication/ForgotPasswordForm.tsx, src/pages/Authentication/LoginForm.tsx, src/pages/Authentication/RegisterForm.tsx, src/pages/Dashboard/DashboardContent.tsx, src/pages/Dashboard/Sidebar.tsx, src/pages/Dashboard/components/ACFormFieldItem.tsx, src/pages/Dashboard/components/InviteModal.tsx, src/pages/Organisation/orgColumns.tsx, src/pages/Profile/profileColumns.tsx, src/pages/Tour/toursColumns.tsx
This PR fixed some UI issue.
- fixed some UI issue.
[JIRA Ticket: IF-343](https://dext.atlassian.net/browse/IF-343)
=> Feature/if 343 fe UI adjustment

src/app/index.css, src/pages/Authentication/EmailVerification/index.tsx, src/pages/Authentication/ForgotPasswordForm.tsx, src/pages/Authentication/LoginForm.tsx, src/pages/Authentication/RegisterForm.tsx, src/pages/Authentication/index.tsx
This PR is for UI responsive adjustment
- root font size for different screen size.
- fixed get token in window.location.href.
- manual test.
[JIRA Ticket: IF-346](https://dext.atlassian.net/browse/IF-346)
=> Bugfix/if 346 fe UI responsive adjustment

src/app/App.tsx, src/components/DataTable/index.tsx, src/components/Header/SignInAvatar.tsx, src/components/Header/index.tsx, src/components/ProtectedRoute/RedirectRoute.tsx, src/constants/errorMessages.ts, src/hooks/auth/useGetMe.ts, src/hooks/contacts/useContact.ts, src/hooks/profiles/useOrgManager.ts, src/hooks/profiles/useOrgTeacher.ts, src/hooks/profiles/useParentWithChildren.ts, src/hooks/profiles/useStudent.ts, src/hooks/useAuth.tsx, src/hooks/usePermissions.ts, src/layouts/MainLayout/index.tsx, src/pages/Authentication/EmailVerification/index.tsx, src/pages/Authentication/LoginForm.tsx, src/pages/Dashboard/DashboardContent.tsx, src/pages/Dashboard/Sidebar.tsx, src/pages/Organisation/OrganisationDetailForm.tsx, src/pages/Profile/ProfileDetailPage.tsx, src/pages/Profile/ProfileForm.tsx, src/queries/auth.ts, src/routes/index.tsx, src/store/index.ts, src/store/useUserStore.ts
This PR linked getMe api to check login state.
- linked getme api.
- setState after update profile.
- manul test.
[JIRA Ticket: IF-238](https://dext.atlassian.net/browse/IF-238)
=> feat: add get me api and adjust state after update profile

src/components/InputFile/index.tsx, src/pages/Authentication/RegisterForm.tsx
This PR added logo image uploader to signup form.
- added input of file type with avatar.
- linked image uploader.
[JIRA Ticket: IF-355](https://dext.atlassian.net/browse/IF-355)
=> feat: add img uploader for signup form

src/constants/apiConfig.ts, src/hooks/auth/useForgotPassword.ts, src/pages/Authentication/EmailSendAnimation.tsx, src/pages/Authentication/EmailVerification/index.tsx, src/pages/Authentication/ForgotPasswordForm.tsx, src/pages/Authentication/LoginForm.tsx, src/pages/Authentication/RegisterForm.tsx, src/services/apiServices/authApis.ts, src/types/auth.ts
This PR linked forgot-password api.
- Linked forgot-password api.
- manul test.
[JIRA Ticket: IF-313](https://dext.atlassian.net/browse/IF-313)
=> feat: linked forgot password

src/constants/apiConfig.ts, src/hooks/auth/useResetPassword.ts, src/pages/Authentication/ForgotPasswordForm.tsx, src/pages/Authentication/LoginForm.tsx, src/pages/Authentication/ResetPassword/index.tsx, src/routes/index.tsx, src/services/apiServices/authApis.ts, src/types/auth.ts
This PR linked reset password.
- linked reset password.
[JIRA Ticket: IF-332](https://dext.atlassian.net/browse/IF-332)
=> feat: linked forget password

src/app/index.css, src/components/DataTable/index.tsx, src/pages/DefaultDashboard/RoleBasedDashboard.tsx, src/pages/DefaultDashboard/index.tsx, src/routes/index.tsx, tailwind.config.js
This PR added dashboard UI.
- added dashboard UI for different roles.
- manul testing.
[JIRA Ticket: IF-361](https://dext.atlassian.net/browse/IF-361)
=> Feature/if 361 fe dashboard UI

.github/workflows/frontend-deploy-prod.yml
Implement generic frontend deployment workflow for multi-environment CI/CD
This PR ...
- Create reusable frontend-deploy.yml workflow for consistent deployment across environments
- Add environment-specific deployment workflows for Dev, UAT, and Production
- Leverage common-action/setup-frontend-aws for AWS configuration
- Configure environment-specific parameters (S3 buckets, CloudFront distributions, URLs)
- Implement standardized deployment verification and notifications
- Support automated deployments via workflow_run and manual via workflow_dispatch
- Improve maintainability by centralizing deployment logic
- Run CI/CD pipeline
[JIRA Ticket: IF-362](https://dext.atlassian.net/browse/IF-362)
=> Add production deployment workflow
